### ISSUE TITLE
Triplicate files, version folders

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie.github.io#93]
Hi,

cloning this repo, I noticed that most files exist three times: **1)** main directory **2)** v2.1 **3)** v3.

Do you want to keep those or can we clean up the structure of this repo (history is preserved in commits anyway)?

**Comment by martinschorb** [comment]
This concerns mostly the tutorials (images etc.).
The specs we probably want to keep.

**Comment by constantinpape** [comment]
> cloning this repo, I noticed that most files exist three times: **1)** main directory **2)** v2.1 **3)** v3.
> 
> Do you want to keep those or can we clean up the structure of this repo (history is preserved in commits anyway)?

Please keep the v2.1 and v.3 folders unchanged. These are there to monitor the exact state of releases.

**Comment by martinschorb** [comment]
The tutorials in the sub-folders also have dead links as `use-cases` do not exist in there.

**Comment by constantinpape** [comment]
> The tutorials in the sub-folders also have dead links as `use-cases` do not exist in there.

Ok, I guess this is missing from my command to create this, since it was just added recently. I will fix it.

(But for adding anything new you don't need to have a look at v0.2.1 or v0.3, I added this because it's a good practice to enable browsing earlier versions of specs, see for example the ngff spec, but they should not be updated unless in order to fix clear bugs like the missing `use-cases` folder.)
